# Generated by Django 4.0.6 on 2022-07-24 10:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'Regular'), (1, 'Sicilian')], default=0)),
                ('smallprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largeprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extrascount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('smallprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largeprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('smallprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largeprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeightedM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartPasta',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='CartPizza',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='CartPlatter',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='CartSalad',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='CartSub',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='OrderPasta',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='OrderPlatter',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('weightedm2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.weightedm2m')),
            ],
            bases=('orders.weightedm2m',),
        ),
        migrations.CreateModel(
            name='SubCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('addons', models.ManyToManyField(to='orders.addon')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='orders.sub')),
            ],
        ),
        migrations.CreateModel(
            name='PlatterCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='orders.platter')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='orders.pizza')),
                ('toppings', models.ManyToManyField(to='orders.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pasta', models.ManyToManyField(related_name='orders', through='orders.OrderPasta', to='orders.pasta')),
                ('pizza', models.ManyToManyField(related_name='orders', through='orders.OrderPizza', to='orders.pizzacombination')),
                ('platter', models.ManyToManyField(related_name='orders', through='orders.OrderPlatter', to='orders.plattercombination')),
                ('salad', models.ManyToManyField(related_name='orders', through='orders.OrderSalad', to='orders.salad')),
                ('sub', models.ManyToManyField(related_name='orders', through='orders.OrderSub', to='orders.subcombination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pasta', models.ManyToManyField(related_name='cart', through='orders.CartPasta', to='orders.pasta')),
                ('pizza', models.ManyToManyField(related_name='cart', through='orders.CartPizza', to='orders.pizzacombination')),
                ('platter', models.ManyToManyField(related_name='cart', through='orders.CartPlatter', to='orders.plattercombination')),
                ('salad', models.ManyToManyField(related_name='cart', through='orders.CartSalad', to='orders.salad')),
                ('sub', models.ManyToManyField(related_name='cart', through='orders.CartSub', to='orders.subcombination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordersub',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.subcombination'),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salad'),
        ),
        migrations.AddField(
            model_name='orderplatter',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderplatter',
            name='platter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.plattercombination'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizzacombination'),
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pasta'),
        ),
        migrations.AddField(
            model_name='cartsub',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='cartsub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.subcombination'),
        ),
        migrations.AddField(
            model_name='cartsalad',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='cartsalad',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salad'),
        ),
        migrations.AddField(
            model_name='cartplatter',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='cartplatter',
            name='platter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.plattercombination'),
        ),
        migrations.AddField(
            model_name='cartpizza',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='cartpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizzacombination'),
        ),
        migrations.AddField(
            model_name='cartpasta',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
        migrations.AddField(
            model_name='cartpasta',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pasta'),
        ),
    ]
