# Generated by Django 4.0.6 on 2022-07-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'carted'), (1, 'placed'), (2, 'delivered')], default=0)),
                ('pasta', models.ManyToManyField(related_name='orders', to='orders.pasta')),
                ('pizza', models.ManyToManyField(related_name='orders', to='orders.pizza')),
                ('platter', models.ManyToManyField(related_name='orders', to='orders.platter')),
                ('salad', models.ManyToManyField(related_name='orders', to='orders.salad')),
                ('sub', models.ManyToManyField(related_name='orders', to='orders.sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
