# Generated by Django 4.0.6 on 2022-07-16 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'placed'), (1, 'completed')], default=0),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.ManyToManyField(related_name='cart', to='orders.pasta')),
                ('pizza', models.ManyToManyField(related_name='cart', to='orders.pizza')),
                ('platter', models.ManyToManyField(related_name='cart', to='orders.platter')),
                ('salad', models.ManyToManyField(related_name='cart', to='orders.salad')),
                ('sub', models.ManyToManyField(related_name='cart', to='orders.sub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
