# Generated by Django 4.0.6 on 2022-07-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SubCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('addons', models.ManyToManyField(to='orders.addon')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='orders.sub')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='orders.pizza')),
                ('toppings', models.ManyToManyField(to='orders.topping')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='pizza',
            field=models.ManyToManyField(related_name='cart', to='orders.pizzacombination'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sub',
            field=models.ManyToManyField(related_name='cart', to='orders.subcombination'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(related_name='orders', to='orders.pizzacombination'),
        ),
    ]
