# Generated by Django 4.0.6 on 2022-07-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_mode_address_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.IntegerField(choices=[(0, 'UPI'), (1, 'Wallets'), (2, 'Credit / Debit / ATM Card'), (3, 'Net Banking'), (4, 'Cash on Delivery')]),
        ),
    ]
