# Generated by Django 4.0.6 on 2022-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completedtime',
            field=models.DateTimeField(null=True),
        ),
    ]
