# Generated by Django 4.0.6 on 2022-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_topping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='extrascount',
            field=models.IntegerField(default=0),
        ),
    ]
