# Generated by Django 4.0.6 on 2022-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pizza_extrascount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzacombination',
            old_name='price',
            new_name='smallprice',
        ),
        migrations.RenameField(
            model_name='subcombination',
            old_name='price',
            new_name='smallprice',
        ),
        migrations.AddField(
            model_name='pizzacombination',
            name='largeprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subcombination',
            name='largeprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
