# Generated by Django 4.0.6 on 2022-07-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_price_pizzacombination_smallprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzacombination',
            old_name='smallprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='subcombination',
            old_name='smallprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pizzacombination',
            name='largeprice',
        ),
        migrations.RemoveField(
            model_name='subcombination',
            name='largeprice',
        ),
        migrations.AddField(
            model_name='pizzacombination',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcombination',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PlatterCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='orders.platter')),
            ],
        ),
    ]
