# Generated by Django 4.0.6 on 2022-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_address_address_addressline_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
