# Generated by Django 4.0.6 on 2022-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_smallprice_pizzacombination_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='platter',
            field=models.ManyToManyField(related_name='cart', to='orders.plattercombination'),
        ),
        migrations.AlterField(
            model_name='order',
            name='platter',
            field=models.ManyToManyField(related_name='orders', to='orders.plattercombination'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub',
            field=models.ManyToManyField(related_name='orders', to='orders.subcombination'),
        ),
    ]
