# Generated by Django 4.0.6 on 2022-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_pizza_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='pizza_images'),
        ),
    ]
