# Generated by Django 4.0.6 on 2022-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='image',
            field=models.ImageField(blank=True, upload_to='pasta_images'),
        ),
        migrations.AddField(
            model_name='platter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platter',
            name='image',
            field=models.ImageField(blank=True, upload_to='platter_images'),
        ),
        migrations.AddField(
            model_name='salad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salad',
            name='image',
            field=models.ImageField(blank=True, upload_to='salad_images'),
        ),
        migrations.AddField(
            model_name='sub',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='image',
            field=models.ImageField(blank=True, upload_to='sub_images'),
        ),
    ]
