# Generated by Django 4.0.6 on 2022-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_pasta_description_pasta_image_platter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
